// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YellowCart.Data;

#nullable disable

namespace YellowCart.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("YellowCart.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantitive")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("YellowCart.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Gaming accessories",
                            SubCategoryName = "Mouse"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Gaming accessories",
                            SubCategoryName = "Keyboard"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Gaming accessories",
                            SubCategoryName = "Play Station"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Gaming accessories",
                            SubCategoryName = "PC And Laptops"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Gaming accessories",
                            SubCategoryName = "Headphones"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Electronics",
                            SubCategoryName = "TV & Audio"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Electronics",
                            SubCategoryName = "Mobile Phones"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Electronics",
                            SubCategoryName = "Fan & Coolers"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Electronics",
                            SubCategoryName = "Heaters"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Men's Fashion",
                            SubCategoryName = "Mens Shirts"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Men's Fashion",
                            SubCategoryName = "Mens Jeans"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Men's Fashion",
                            SubCategoryName = "Watches"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Women's Fashion",
                            SubCategoryName = "Women's Shirts"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Women's Fashion",
                            SubCategoryName = "Women's Jeans"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Women's Fashion",
                            SubCategoryName = "Shalwars"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Accessories",
                            SubCategoryName = "Others"
                        });
                });

            modelBuilder.Entity("YellowCart.Models.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantitive")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("YellowCart.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5L,
                            Description = "This gaming headset comes with a bendable cardioid noise-canceling microphone. The closed ear cup design effectively reduces background noise interference, allowing you to communicate seamlessly with your teammates without interruption.",
                            Image = "/images/GamingHeadset.jpg",
                            Price = 4500,
                            ProductName = "Gaming Headset with Mic - Compatible with PS5",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1L,
                            Description = "59G ULTRA-LIGHTWEIGHT DESIGN — Enjoy a level of speed and control favored by the world’s top players with one of the lightest ergonomic esports mice ever created",
                            Image = "/images/Mouse.jfif",
                            Price = 1200,
                            ProductName = "Wired Gaming Mouse",
                            Quantity = 56
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1L,
                            Description = "Pentakill, 5 DPI Levels - Geared with 5 redefinable DPI levels (default as: 500/1000/2000/3000/4000), easy to switch between different game needs. Dedicated demand of DPI options between 500-8000 is also available to be processed by software.",
                            Image = "/images/mouse2.jpg",
                            Price = 2500,
                            ProductName = "Redragon M612 Predator RGB Gaming Mouse",
                            Quantity = 30
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3L,
                            Description = "Ready to play as USB AC adaptor is included that supports 5 V, 1.0A USB output",
                            Image = "/images/playstation.jfif",
                            Price = 250000,
                            ProductName = "Sony PlayStation ",
                            Quantity = 12
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4L,
                            Description = "COMPATIBILITY - This hard shell laptop case is custom-made only to fit Dell Chromebook 3110/3100 11-inch (2-in-1). Incompatible with other device models. Please don't hesitate to reach out if you need further assistance.",
                            Image = "/images/chrome.jfif",
                            Price = 450000,
                            ProductName = "SlimTech Laptop Case Fits Dell Chromebook",
                            Quantity = 35
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2L,
                            Description = "ROX Gaming keyboard with LEDs",
                            Image = "/images/keyboard.jpg",
                            Price = 3000,
                            ProductName = "Gaming Keyboard",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 6L,
                            Description = "Products with electrical plugs are designed for use in the US. Outlets and voltage differ internationally and this product may require an adapter or converter for use in your destination. Please check compatibility before purchasing.",
                            Image = "/images/insignia.jpg",
                            Price = 75000,
                            ProductName = "INSIGNIA 32-inch Class F20 Series Smart HD 720p Fire TV",
                            Quantity = 12
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 6L,
                            Description = "WORKS WITH ALEXA & SIRI - WiiM Mini works with Alexa and Siri Voice Assistants. Use your voice to control music playback and smart home automation.",
                            Image = "/images/51797CctBoL._AC_SX679_.jpg",
                            Price = 25000,
                            ProductName = "WiiM Mini AirPlay2 Wireless Audio Streamer, Multiroom Stereo, Preamplifier",
                            Quantity = 200
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6L,
                            Description = "Products with electrical plugs are designed for use in the US. Outlets and voltage differ internationally and this product may require an adapter or converter for use in your destination. Please check compatibility before purchasing.",
                            Image = "/images/61i2nXFwvXL._AC_SX679_.jpg",
                            Price = 4500,
                            ProductName = "Car Radio with Bluetooth, Car Audio Receiver",
                            Quantity = 78
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 7L,
                            Description = "4G Android 11 Mobile Phone, 5.5 Inch HD Display, 13MP + 5MP Camera, 3100mAh Battery, 2GB/16GB, 128GB Expandable, Dual SIM Black",
                            Image = "/images/71D08-YlM2L._AC_SX679_.jpg",
                            Price = 80000,
                            ProductName = "CUBOT Note 8 Smartphone Without Contract, 4G Android 11 Mobile Phone",
                            Quantity = 300
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 7L,
                            Description = "Power 5 (3+64g) Android 11 Smart Phone, 6150mAh Battery+ 6.53\" HD Display Smartphone with 16MP AI Triple Camera, Dual SIM Android Phone",
                            Image = "/images/71IvlUbzpqL._AC_SX679_.jpg",
                            Price = 70000,
                            ProductName = "UMIDIGI Unlocked Cell Phone",
                            Quantity = 300
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 7L,
                            Description = "Factory Unlocked Android Smartphone, 128GB w/ 6.4” Fluid Display Screen, Hi Res Camera, Long Battery Life, Refined Design, US Version, 2023, Awesome Black",
                            Image = "/images/61MEp5HIdBL._AC_SX679_.jpg",
                            Price = 90000,
                            ProductName = "SAMSUNG Galaxy A54 5G A Series Cell Phone",
                            Quantity = 480
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 10L,
                            Description = "SOFT & LIGHTWEIGHT - Super-soft and lightweight fabric feels great up against your skin.\r\nSHORT-SLEEVES - Sporty short-sleeve design keeps you feeling cool and comfortable.",
                            Image = "/images/81vCTr9UaEL._AC_UX679_.jpg",
                            Price = 1200,
                            ProductName = "Hanes Men’s Short Sleeve Graphic T-shirt Collection",
                            Quantity = 950
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 10L,
                            Description = "HIGH-QUALITY MATERIAL --- Button down shirt lightweight, soft and comfortable, casual, skin-friendly, relaxed fit, perfectly suitable for all seasons.",
                            Image = "/images/81oTmSS7J3L._AC_UX569_.jpg",
                            Price = 750,
                            ProductName = "COOFANDY Men's Casual Linen Button Down Shirt Short Sleeve Beach Shirt",
                            Quantity = 30
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 13L,
                            Description = "Material: Womens Tops and Blouses is Made of Rayon/Polyester/Spandex. The Women Summer Casual Shirt Feels Very Soft and Comfortable. It Is a Breathable but Opaque Womens Short Sleeve T Shirts.\r\nFeature: This Summer Casual Short Sleeve Shirt designs with Leopard Print, Color Blocks, Round Neck Combined with Stylish Short Sleeve Design, Women Crew Neck Color Block, Reflects the Elegance of Women.",
                            Image = "/images/7104Xrswi+L._AC_UY741_.jpg",
                            Price = 850,
                            ProductName = "Adibosy Women Summer Casual Shirts: Short Sleeve Striped Tunic Tops - Womens Crew Neck Tee Tshirt Blouses",
                            Quantity = 1000
                        });
                });

            modelBuilder.Entity("YellowCart.Models.ReviewRatings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ReviewRatings");
                });

            modelBuilder.Entity("YellowCart.Models.ShippingAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShippingAddresses");
                });

            modelBuilder.Entity("YellowCart.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YellowCart.Models.Cart", b =>
                {
                    b.HasOne("YellowCart.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YellowCart.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YellowCart.Models.Orders", b =>
                {
                    b.HasOne("YellowCart.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YellowCart.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YellowCart.Models.Product", b =>
                {
                    b.HasOne("YellowCart.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("YellowCart.Models.ReviewRatings", b =>
                {
                    b.HasOne("YellowCart.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YellowCart.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YellowCart.Models.ShippingAddress", b =>
                {
                    b.HasOne("YellowCart.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
